modLoader="javafml"
loaderVersion="[43,)"
license="MIT"

[[mods]]
modId="bgames_library"
version="0.0.1"
displayName="bGames Library"
authors="Gsimken"

[[dependencies.bgames_library]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




